### ISSUE TITLE
unexpected error error="field 'fields' is a reserved name in BinData::Array"

### ISSUE THREAD

**Issue by moduspwnens** [repeatedly/fluent-plugin-netflow#18]
Apologies if I'm misunderstanding here.
I get this error when I start td-agent.

unexpected error error="field 'fields' is a reserved name in BinData::Array"

Full log here:
[td-agent.txt](https://github.com/repeatedly/fluent-plugin-netflow/files/364861/td-agent.txt)

I'm using Ubuntu 16.04 (on AWS, us-east-1, ami-ddf13fb0). Here's a bash script that can be run from a fresh boot that recreates the problem.
[fluentd-netflow-setup.txt](https://github.com/repeatedly/fluent-plugin-netflow/files/364868/fluentd-netflow-setup.txt)

Is there something obvious I'm doing wrong?

**Comment by moduspwnens** [comment]
I'm not super familiar with Ruby, but it looks like if I install an earlier version of BinData before installing the plugin, I no longer get this error.

/opt/td-agent/embedded/bin/fluent-gem install bindata -v 2.1.0
/opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-netflow

**Comment by repeatedly** [comment]
Thanks for the report!
I will check it later after LinuxCon.

**Comment by moduspwnens** [comment]
Thanks. I also just tried with bindata version 2.3.0 and that worked, too.

**Comment by codeout** [comment]
It's likely that a strict keyword validation introduced at bindata 2.3.1 causes the error.
https://github.com/dmendel/bindata/blob/master/lib/bindata/struct.rb#L73

We need a patch to work around the reserved word.

**Comment by repeatedly** [comment]
I just released v0.2.3 including https://github.com/repeatedly/fluent-plugin-netflow/pull/19 .
This issue should be resolved.
