### ISSUE TITLE
Address already in use.

### ISSUE THREAD

**Issue by nvasion** [repeatedly/fluent-plugin-netflow#3]
I upgraded to 0.0.4 but now there is an error with this [error]: unexpected error error_class=Errno::EADDRINUSE error=#<Errno::EADDRINUSE: Address already in use - bind(2)

Have not changed config. It was working in .3 but now not in .4

**Comment by repeatedly** [comment]
Error shows you use same address/port.
Maybe previous process is still alive or other product use same address/port.
v0.0.4 doesn't touch network related code so version is not related.
