### ISSUE TITLE
Error while loading plugin

### ISSUE THREAD

**Issue by Theoooooo** [repeatedly/fluent-plugin-netflow#39]
Packages installed :

- Ruby (lastest version from repository)
- latest bindata library though gem
- the netflow plugin though gem (as said in the documentation)
- latest td-agent version though the repository (2.3.6) and i also test it with the latest .deb (3.3.0)

After installing the plugin with the gem command and configured my .conf file, i got the following errors when i launch the service (sorry the logs are a bit messed up ^^)  :

mars 28 11:37:12 cyres-log fluentd[18562]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fluent/plugin/parser_netflow (LoadError)
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /etc/td-agent/plugin/in_netflow.rb:20:in `<top (required)>'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/registry.rb:68:in `search'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/registry.rb:44:in `lookup'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin.rb:146:in `new_impl'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin.rb:100:in `new_input'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:277:in `add_source'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:122:in `block in configure'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:118:in `each'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:118:in `configure'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/engine.rb:131:in `configure'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/engine.rb:96:in `run_configure'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:795:in `run_configure'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:579:in `dry_run'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:597:in `supervise'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:502:in `run_supervisor'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/bin/fluentd:8:in `<top (required)>'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/bin/fluentd:23:in `load'
mars 28 11:37:12 cyres-log fluentd[18562]:         from /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
mars 28 11:37:12 cyres-log systemd[1]: td-agent.service: Control process exited, code=exited status=1
mars 28 11:37:12 cyres-log systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.

If you need more precise information or logs from the event journal, let me know

**Comment by repeatedly** [comment]
https://docs.fluentd.org/v1.0/articles/faq#i-installed-td-agent-and-want-to-add-custom-plugins.-how-do-i-do-it?

This one?

**Comment by Theoooooo** [comment]
Yeah i wasn't using the good command to install it. I didn't see the "td-agent-gem" section.
Sorry about that
