### ISSUE TITLE
Sample configuration in README does not work

### ISSUE THREAD

**Issue by narutaro** [repeatedly/fluent-plugin-netflow#6]
The portion `versions [5, 9]` in the sample configuration in the README causes `Ignoring Netflow version v#{header.version}` error. It seems that `[5, 9]` here is dealed as `String` object in `parser_netflow.rb`. `version 5.9` or simply deleting this line worked for me. 

my env:
'fluent-plugin-netflow' version '0.1.1'
'fluentd' version '0.12.18'

Thanks for the great plugin. Happy holiday!

**Comment by repeatedly** [comment]
Thx for the report. I just fixed.
